### PR TITLE
Home

### PR DESCRIPTION
**Pull request by Abhinay-Dodda**

### CODE REVIEW

**Comment by reddyeswar2002** [comment]
there no information in "About us" add some information in that and in "faqs" and there is no number in the" Contact us"

**Review by reddyeswar2002 — COMMENTED** [review]
no info in about us and about us

**Review by Koushik-varma — APPROVED** [review]
The login form checks credentials but only outputs a generic alert message upon failure.

- You can make the error message more descriptive (though not too specific for security reasons).
- Additionally, consider limiting login attempts to prevent brute force attacks using rate limiting.

**Review by Koushik-varma — CHANGES_REQUESTED** [review]
Add the details, mentioned by eswar.

**Review by Koushik-varma — APPROVED** [review]

**Pull request merged**
